### ISSUE TITLE
BUG: The link to GH profile doesn't work.

### ISSUE THREAD

**Issue by Mopsior** [wybran/wybran.github.io#1]
Button "Github Profile" doesn't work. It's redirecting to https://github.com/Wybranowsky, but your link is [https://github.com/wybran](https://github.com/wybran).

**Comment by mtatko** [comment]
They changed their name recently, so they probably didn't notice. I've created a PR and let him know.

**Comment by wybran** [comment]
Wielkie dzięki byczki co ja bym bez was <333 btw @Mopsior jesteś z elektrona?

**Comment by Mopsior** [comment]
> Wielkie dzięki byczki co ja bym bez was <333 btw @Mopsior jesteś z elektrona?

Będę od września 😉

**Comment by wybran** [comment]
O to super, mamy taki mini team programistów elektrona i właśnie pracujemy nad nową stroną szkoły, możesz obserwować a nawet do nas dołączyć przedpremierowo xd: https://github.com/ElektronPlus

**Comment by Mopsior** [comment]
> O to super, mamy taki mini team programistów elektrona i właśnie pracujemy nad nową stroną szkoły, możesz obserwować a nawet do nas dołączyć przedpremierowo xd: https://github.com/ElektronPlus

Dzięki za zaproszenie, zobaczę bo aktualnie trochę u mnie krucho z czasem ale może w czerwcu 🤔 Jakby co, wbije teraz do was na discorda, dm mam otwarte
